name: rupia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.4.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Routing
  go_router: ^14.2.0
  
  # UI & UX
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  
  # Firebase & Auth
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.1
  firebase_crashlytics: ^5.0.6
  firebase_analytics: ^12.1.0
  firebase_storage: ^13.0.5
  
  # Charts
  fl_chart: ^0.68.0
  
  # HTTP & Storage
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  
  # Camera & OCR
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.0.7
  
  # Location & Geofencing
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.0.0
  
  # v3.0 - PDF & Excel Export
  pdf: ^3.10.8
  printing: ^5.14.2
  excel: ^4.0.3
  open_file: ^3.5.10
  
  # v3.0 - Widgets
  home_widget: ^0.6.0
  
  # v3.1 - ML & AI
  tflite_flutter: ^0.10.4
  
  # v3.1 - File handling
  file_picker: ^8.0.0+1
  archive: ^3.6.1
  share_plus: ^10.1.4
  
  # Utilities
  intl: any
  uuid: ^4.4.0
  collection: ^1.18.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # Code Generation (disabled for simpler setup)
  # isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  # riverpod_generator: ^2.4.0
  # freezed: ^2.5.2
  # json_serializable: ^6.8.0
  
  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Android 5.0
  
  # Adaptive icon (Android 8.0+)
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/logo.png"
  
  # iOS specific
  remove_alpha_ios: true
  
  # Web
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#6366F1"
    theme_color: "#6366F1"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
